Store open and close hours update issue fixing
aligent/magento-stockists-module pull request #1
Opened 2021-04-15 05:09 UTC by irfanjamion

when saving store details Store open and close hours not saving. Fixing those issues.

2021-04-15 05:54 UTC, toddhainsworth commented on Ui/DataProvider/Stockist.php
> +use Magento\Framework\Serialize\SerializerInterface;
Are we happy to use the interface instead of explicitly using the JSON serializer? I think this is a scenario where we would want to directly use `\Magento\Framework\Serialize\Serializer\Json` to ensure we're getting the JSON serializer. The scenario I'm thinking of is where Magento decides to switch default serializers, changes it's di-preference for this interface to be XML or YML or whatever else and suddenly we can't read or write the opening hours. Thoughts, @brettlaishley ?

2021-04-15 05:58 UTC, peter-aligent commented on view/adminhtml/ui_component/stockist_form.xml
> +                    <link>https://jsonformatter.org/</link>
Here is a link to the outside website. 
Hi @aligent-lturner . Wondering if it's okay to use it? Or should we avoid to put outside links?

2021-04-15 06:00 UTC, aligent-lturner commented on Ui/DataProvider/Stockist.php
> +use Magento\Framework\Serialize\SerializerInterface;
Definitely want to use `Json` specifically here

2021-04-15 06:06 UTC, aligent-lturner requested changes

2021-04-15 06:06 UTC, aligent-lturner commented on Ui/DataProvider/Stockist.php
> +use Magento\Framework\Serialize\SerializerInterface;
Alternatively, use `di.xml` to specify that the parameter is specifically the `Json` class

2021-04-15 06:06 UTC, aligent-lturner commented on Model/Stockist/DataProcessor/TradingHours.php
> +use Magento\Framework\Serialize\SerializerInterface;
Same issue as @toddhainsworth flagged on `Stockist.php` - need to ensure this is the `Json` serializer.

2021-04-15 06:08 UTC, peter-aligent commented on view/adminhtml/ui_component/stockist_form.xml
> +                    <link>https://jsonformatter.org/</link>
Thanks @aligent-lturner.
@irfanjamion Please remove this link. Thanks.

2021-04-15 06:12 UTC, peter-aligent commented on view/adminhtml/ui_component/stockist_form.xml
> +                        Before Adding hours go into https://jsonformatter.org/ and validate format is correct</description>
Can we have a full example data here? Monday to Sunday, that can be a template for the person who inputs this value. 
Suggest to change "08:00 to 09:30" to "08:00 AM to 09:30 PM", or "08:00 to 21:30".

If we get more time, we can change it to a custom field (a grid for the details instead of a text field).

2021-04-15 07:50 UTC, brettlaishley commented on Ui/DataProvider/Stockist.php
> +use Magento\Framework\Serialize\SerializerInterface;
Yeah that's why I tagged a few other people for code review, I just remember seeing some deprecated no-nos around json serializing... but based on what you've described I would be inclined to import the `Serializer\Json` class to ensure we always get the same serialization

2021-04-18 23:59 UTC, irfanjamion commented on Ui/DataProvider/Stockist.php
> +use Magento\Framework\Serialize\SerializerInterface;
`Magento\Framework\Serialize\Serializer\Json` added into di.xml

2021-04-18 23:59 UTC, irfanjamion commented on view/adminhtml/ui_component/stockist_form.xml
> +                    <link>https://jsonformatter.org/</link>
Thanks @peter-aligent @aligent-lturner link is removed.

2021-04-19 00:05 UTC, irfanjamion commented on Model/Stockist/DataProcessor/TradingHours.php
> +use Magento\Framework\Serialize\SerializerInterface;
Thanks @aligent-lturner 
Magento\Framework\Serialize\Serializer\Json added into di.xml

2021-04-19 00:05 UTC, irfanjamion commented on view/adminhtml/ui_component/stockist_form.xml
> +                        Before Adding hours go into https://jsonformatter.org/ and validate format is correct</description>
Thanks @peter-aligent 
description is updated.

2021-04-19 01:03 UTC, toddhainsworth approved these changes

2021-04-19 01:41 UTC, aligent-lturner approved these changes

2021-04-19 01:42 UTC, peter-aligent commented on view/adminhtml/ui_component/stockist_form.xml
> +                        Before Adding hours go into https://jsonformatter.org/ and validate format is correct</description>
Could you please remove https://jsonformatter.org/ as well? Thanks.

2021-04-19 02:56 UTC, irfanjamion commented on view/adminhtml/ui_component/stockist_form.xml
> +                        Before Adding hours go into https://jsonformatter.org/ and validate format is correct</description>
@peter-aligent this is fixed now.
thanks

2021-04-19 03:08 UTC, peter-aligent approved these changes

2021-04-19 03:32 UTC, brettlaishley approved these changes

2021-04-19 03:34 UTC, merged