Add new field into module
aligent/magento-stockists-module pull request #2
Opened 2021-04-30 02:50 UTC by irfanjamion

Adding new field into module

2021-04-30 04:57 UTC, aligent-lturner requested changes
@irfanjamion can you please update the PR description with more information about the changes that are being made and why?

2021-04-30 04:57 UTC, aligent-lturner commented on Api/Data/StockistInterface.php
> +    const SUBURB = 'suburb';
What's the need for this? Generally, `city` would be used for a suburb

2021-04-30 04:57 UTC, aligent-lturner commented on Api/Data/StockistInterface.php
> +     * @return string
If this can return null, then the PHPDoc should reflect that.
Same goes for other functions below

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist.php
> +        return $this;
`setData` already returns the current class - this should just be:
`return $this->setData('description', $description);`

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist.php
> +        $this->setData('gallery', $gallery);
As per comment above.

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist.php
> +    public function getAllowStoreDelivery(): ?bool
The implementation doesn't match the declared return type (in either way)
 - PHPDoc says it returns a string
 - Return type declaration says it's a bool or null
 - Function only ever returns a bool

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist/DataProcessor/Coordinate.php
> +class Coordinate implements \Aligent\Stockists\Api\Data\StockistDataProcessorInterface
Can we add a `use` for this interface to make it easier to read here and below, please?

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist/DataProcessor/TradingHours.php
> +class TradingHours implements \Aligent\Stockists\Api\Data\StockistDataProcessorInterface
Same again - please add a `use` directive for the interface.

2021-04-30 04:57 UTC, aligent-lturner commented on Model/Stockist/Hydrator.php
> +        if (isset($data['allow_store_delivery']) && $data['allow_store_delivery'] == 'true') {
If you want to compare to the string `true`, then this should use `===` instead of `==`

2021-04-30 04:57 UTC, aligent-lturner commented on Ui/DataProvider/Stockist.php
> +            $item['allow_store_delivery'] = isset($item['allow_store_delivery']) && $item['allow_store_delivery'] == 1;
`===` instead of `==`

2021-04-30 04:57 UTC, aligent-lturner commented on etc/schema.graphqls
> +    geolocation_status : Boolean  @doc(description: "Geolocation Option Enabled/Disable")
I'm not sure what these values are for, but they won't be added to the result of the `storeConfig` query without being added to `Magento\StoreGraphQl\Model\Resolver\Store\StoreConfigDataProvider` in `graphql/di.xml`

2021-05-02 20:28 UTC, irfanjamion commented on Api/Data/StockistInterface.php
> +    const SUBURB = 'suburb';
in other country like New Zealand used both field

2021-05-02 21:22 UTC, irfanjamion commented on Api/Data/StockistInterface.php
> +     * @return string
fixing with return format

2021-05-02 21:22 UTC, irfanjamion commented on Model/Stockist.php
> +        return $this;
fixed according to comments

2021-05-02 21:23 UTC, irfanjamion commented on Model/Stockist.php
> +        $this->setData('gallery', $gallery);
fixed according to comments

2021-05-02 21:23 UTC, irfanjamion commented on Model/Stockist.php
> +    public function getAllowStoreDelivery(): ?bool
fixed according to comments

2021-05-02 21:23 UTC, irfanjamion commented on Model/Stockist/DataProcessor/Coordinate.php
> +class Coordinate implements \Aligent\Stockists\Api\Data\StockistDataProcessorInterface
fixed according to comments

2021-05-02 21:24 UTC, irfanjamion commented on Model/Stockist/DataProcessor/TradingHours.php
> +class TradingHours implements \Aligent\Stockists\Api\Data\StockistDataProcessorInterface
fixed according to comments

2021-05-02 21:24 UTC, irfanjamion commented on Model/Stockist/Hydrator.php
> +        if (isset($data['allow_store_delivery']) && $data['allow_store_delivery'] == 'true') {
fixed according to comments

2021-05-02 21:24 UTC, irfanjamion commented on Ui/DataProvider/Stockist.php
> +            $item['allow_store_delivery'] = isset($item['allow_store_delivery']) && $item['allow_store_delivery'] == 1;
fixed according to comments

2021-05-02 21:24 UTC, irfanjamion commented on etc/schema.graphqls
> +    geolocation_status : Boolean  @doc(description: "Geolocation Option Enabled/Disable")
removed StoreConfig unused values

2021-05-02 22:10 UTC, irfanjamion commented
> @irfanjamion can you please update the PR description with more information about the changes that are being made and why?
adding new field into stockists module which is used into KMD project. this field will help to future module.
url_key used to add for seo friendly url for PWA
suburb field use for other country
gallery for add gallery image etc.

2021-05-02 23:15 UTC, aligent-lturner commented on Model/Stockist.php
> +        return $this;
This doesn't seem to have been changed at all?

2021-05-02 23:17 UTC, aligent-lturner commented on Model/Stockist/DataProcessor/TradingHours.php
> +class TradingHours implements stockistDataProcessorInterface
Incorrect casing here - needs uppercase `S`

2021-05-02 23:19 UTC, aligent-lturner commented on Model/Stockist.php
> +use phpDocumentor\Reflection\Types\Boolean;
This seems like an accidental import?

2021-05-02 23:23 UTC, aligent-lturner commented on Model/Stockist.php
> +        return $this;
Ignore this - was looking at the original commit.

2021-05-03 23:45 UTC, irfanjamion commented on Model/Stockist/DataProcessor/TradingHours.php
> +class TradingHours implements stockistDataProcessorInterface
@aligent-lturner thanks for correcting this. i have fixed in code, Please check this again .

2021-05-03 23:45 UTC, irfanjamion commented on Model/Stockist.php
> +use phpDocumentor\Reflection\Types\Boolean;
@aligent-lturner thanks for correcting this. i have fixed in code, Please check this again .

2021-05-04 00:22 UTC, aligent-lturner approved these changes

2021-05-04 00:41 UTC, merged