Add geocoding API region biasing control
aligent/magento-stockists-module pull request #25
Opened 2022-06-24 06:21 UTC by derrick-deng-aligent

Adds an admin area toggle to decide whether or not to use the region biasing feature from the Google geocoding service

Ticket in the back-end board: https://aligent.atlassian.net/browse/BEG-82
![Recording 2022-06-24 at 15 40 18](https://user-images.githubusercontent.com/100173186/175474881-7b3686b9-133f-426b-80b2-6882c0c0efb4.gif)

2022-06-24 06:34 UTC, brettlaishley commented on etc/adminhtml/system.xml
> +                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
Maybe you could add a `<comment>` here to explain what this does. Same as the `url` attribute above. Including this link would be helpful to the admin user.

https://developers.google.com/maps/documentation/geocoding/requests-geocoding#RegionCodes

2022-06-24 06:36 UTC, aligent-lturner requested changes

2022-06-24 06:36 UTC, aligent-lturner commented on Service/GeocodeStockist.php
> +            if (!$this->isApiBiasingEnabled()) {
I don't think this is the right place for this check. If region biasing is disabled, it should still be performing the geocoding request (if the address has changed), it just shouldn't include the region biasing in the request.

I would think that within the adapter's `buildRequest` function is where you want to add the check.

2022-06-24 06:36 UTC, aligent-lturner commented on Service/GeocodeStockist.php
> +        return (bool)$this->scopeConfig->getValue(self::XML_PATH_ENABLE_API_BIASING, ScopeInterface::SCOPE_STORE);
`ScopeConfigInterface` has a function called `isSetFlag`, which returns a boolean - you can use this instead of `getValue` and remove the cast

2022-06-24 06:39 UTC, derrick-deng-aligent commented on Service/GeocodeStockist.php
> +                return;
@brettlaishley I thought 

> Please add the optional region parameter to $queryParams in \Aligent\Stockists\Model\GoogleMapsAdapter::buildRequest to reduce errors.

 would have to be in a separate PR.

I'll have it included in this one too :D

2022-06-24 08:48 UTC, brettlaishley commented on Model/ResourceModel/Stockist.php
> +        $openingHours = $object->getData(StockistInterface::HOURS) ? $object->getData(StockistInterface::HOURS)->getData() : null;
@derrick-deng-aligent nice catch. I was really scrutinising this code because I could see @aligent-lturner changed it from this as part of the v2 upgrade and it slipped through code review, but evidently it's an easily missed `->getData()` after the `?` :grin:

I wonder if we should change the code to this so it's a bit easier to digest and not prone to accidental wrong refactoring in the future.
```
        $openingHours = $object->getData(StockistInterface::HOURS) ?? null;
        if ($openingHours) {
            $hoursData = $openingHours->getData();
            $object->setData('hours', $this->json->serialize($hoursData));
        }
```

2022-06-27 04:24 UTC, derrick-deng-aligent commented on etc/adminhtml/system.xml
> +                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
`<comment>` added

2022-06-27 04:30 UTC, derrick-deng-aligent commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
Calls  `$this->stockistRepository->getById($stockistId)` to get the stockist from the database to compare the difference with the one we're instantiating from the request params instead of using 
```
\Magento\Framework\Model\AbstractModel::dataHasChangedFor
    public function dataHasChangedFor($field)
    {
        $newData = $this->getData($field);
        $origData = $this->getOrigData($field);
        return $newData != $origData;
    }
```
as `$this->getOrigData($field) `is always returning null

2022-06-27 05:20 UTC, aligent-lturner requested changes

2022-06-27 05:20 UTC, aligent-lturner commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
@derrick-deng-aligent rather than loading the stockist again, I would prefer the problem - `getOrigData()` returning null - be fixed.
I'm assuming that this problem is presenting itself when saving via admin, in which case I'd recommend looking at https://github.com/aligent/magento-stockists-module/blob/main/Model/Stockist/Hydrator.php

2022-06-27 05:48 UTC, brettlaishley commented on Model/GoogleMapsAdapter.php
> +
Blank link here that would be better to remove.

2022-06-27 05:48 UTC, brettlaishley commented on Model/GoogleMapsAdapter.php
> +            $components = $this->buildComponents($stockist);
@aligent-lturner you'll have to comment as to whether you want this, because in my original change request I was only wanting to send the optional `region` parameter:
```
        $queryParams = [
            'address' => $address,
            'key' => $key,
        ];

        if ($this->isApiBiasingEnabled()) {
            $queryParams['region'] = $stockist->getCountry();
        }
```

This component filtering feels like a stronger version of region biasing, and instead of favouring the region it simply won't return results outside of this region? If this is the case we're kind of doubling up with unnecessary work right?

If we want to go down the component filtering method instead I'm fine with that. But we should just update the `system.xml` changes to reflect that we're performing component filtering instead of region biasing and change the link as well.

2022-06-27 06:23 UTC, aligent-lturner requested changes

2022-06-27 06:23 UTC, aligent-lturner commented on Model/GoogleMapsAdapter.php
> +            $components = $this->buildComponents($stockist);
I think we could potentially give the option. Rather than just a yes/no, could have a select called something like "Response Options" with the options of `None`, `Region Biasing` and `Component Filtering`. You're correct that there's no point in doing both.

2022-06-27 06:23 UTC, aligent-lturner commented on Model/GoogleMapsAdapter.php
> +            'country:' . $stockist->getCountry(),
Might want to check that country and postcode are populated before adding them as components. I can imagine that if an empty component was added, it could cause issues.

2022-06-27 06:29 UTC, brettlaishley commented on Model/GoogleMapsAdapter.php
> +            $components = $this->buildComponents($stockist);
Sounds like a good idea. So to clarify @derrick-deng-aligent, we always want to send the `address` and `key` parameters. Then we send either nothing extra, `region`, or `components` additional parameters depending on what they select in the `system.xml` (soon to be) drop down field, with some additional checks wherever required for `null` situations like Lachlan has described in another comment.

Sing out if you have any questions on how to do this :)

2022-06-27 06:59 UTC, derrick-deng-aligent commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
@aligent-lturner when hydrating the data https://github.com/aligent/magento-stockists-module/blob/main/Model/Stockist/Hydrator.php it doesn't seem to load the stockist, but uses ` $this->dataObjectHelper->populateWithArray()`  to populate the stockist data object

2022-06-27 07:18 UTC, derrick-deng-aligent commented on Model/GoogleMapsAdapter.php
> +            $components = $this->buildComponents($stockist);
@brettlaishley I reckon I'll have some questions about the wording on the select label and comment :laughing:

2022-06-28 02:38 UTC, derrick-deng-aligent commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
@aligent-lturner In this case I think it would be a better approach to load the stockist in `Hydrator::hydrate` (if `stockist_id` is populated) rather than in `GoogleMapsAdapter::addressHasChangedFor`

2022-06-28 02:50 UTC, aligent-lturner commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
@derrick-deng-aligent I haven't debugged ui components for a while, but you might want to look at  https://github.com/aligent/magento-stockists-module/blob/main/Ui/DataProvider/Stockist.php also - specifically the `getSearchResult` function. I've got a feeling that what we want is a collection processor so that when the repository's `getList` function is called, we set the original data on all of the entries.

Would need a bit of debugging to work out the exact path the code is taking though.

2022-06-28 06:05 UTC, derrick-deng-aligent commented on Model/GoogleMapsAdapter.php
> +            $newData = $stockist->getData($field);
@aligent-lturner Hope this is the collection processor you mentioned above It seems to set up the original data when `getList` is called
![Screenshot from 2022-06-28 15-29-27](https://user-images.githubusercontent.com/100173186/176104417-89e184b3-a8dc-45c8-8800-16dedb62ee6b.png)

2022-06-28 23:18 UTC, aligent-lturner requested changes
@derrick-deng-aligent just a couple of small points

2022-06-28 23:18 UTC, aligent-lturner commented on Controller/Adminhtml/Index/Save.php
> +                $stockist = $this->stockistRepository->getById((int)$stockistId);
Might need to have a try/catch around this to handle the (unlikely but possible) case where a stockist was present when someone loaded the edit page, but deleted before they saved. I think in that case, you probably want to add an error message via `messageManager` and bail out.

2022-06-28 23:18 UTC, aligent-lturner commented on Model/StockistRepository.php
> +            if ($stockist->getStockistId()) {
Should be `if ($stockist->getIdentifier()) {` ?

2022-07-06 08:07 UTC, brettlaishley commented on Model/Stockist/DataProcessor/TradingHours.php
>              $this->json->unserialize($data[StockistInterface::HOURS]) : "{}";
You've indented everything else because of the if statement, you should also indent this one as well :)

2022-10-10 01:48 UTC, brettlaishley commented on Controller/Adminhtml/Index/Save.php
> +                $stockist = $this->stockistRepository->getById((int)$stockistId);
@derrick-deng-aligent are you still planning to address this concern?

2022-10-14 04:34 UTC, derrick-deng-aligent commented on Controller/Adminhtml/Index/Save.php
> +                $stockist = $this->stockistRepository->getById((int)$stockistId);
@aligent-lturner  I didn't notice my comments were pending for months, thanks @brettlaishley again for helping me out with this!

2022-10-16 22:14 UTC, aligent-lturner approved these changes

2022-10-17 01:19 UTC, brettlaishley approved these changes

2022-10-17 03:30 UTC, derrick-deng-aligent commented
I am not authorized to merge this pull request. Could anyone please do the honors?

2022-10-17 04:03 UTC, merged

2022-10-18 00:11 UTC, brettlaishley commented
@aligent-lturner, in hindsight, we could benefit from a PR template or something that provokes the developer to update the README file :)