Feature/save region by name not id
aligent/magento-stockists-module pull request #9
Opened 2021-07-21 09:19 UTC by brettlaishley

At the moment the region_id is saved to the region field, instead of the full region name like `'South Australia'`, this PR allows the DB entry and hence graphql queries to return a nice name instead of a meaningless ID.

Also fixes a bug where the `'State/Province'` field shows as a text input all the time instead of when the selected country requires a region to be selected  ...  It does not auto populate the region on first load of the page, but it does force the user to select a region when they switch the country away from Australia and back to Australia.

2021-07-21 23:12 UTC, aligent-lturner requested changes
Just the one change needed

2021-07-21 23:12 UTC, aligent-lturner commented on Model/Stockist/Hydrator.php
> +            $region = $this->regionFactory->create()->load($data[StockistInterface::REGION_ID]);
Don't call the `load` function on the model itself - it's deprecated. Instead, inject the resource model and call its `load` function.

2021-07-22 02:02 UTC, brettlaishley commented on Model/Stockist/Hydrator.php
> +            $region = $this->regionFactory->create()->load($data[StockistInterface::REGION_ID]);
Added the changes, as well as fixing another bug I found.

2021-07-22 04:24 UTC, aligent-lturner submitted a review, later dismissed

2021-07-22 05:52 UTC, aligent-lturner approved these changes

2021-07-22 07:01 UTC, brettlaishley commented
If someone could approve the final changes I've brought in that would be great, I've stopped tinkering with the branch now.

2021-07-22 08:13 UTC, aligent-lturner approved these changes

2021-07-22 08:14 UTC, merged